### ISSUE TITLE
配置参数里aesKeyPasswd从哪取

### ISSUE THREAD

**Issue by Jetereting** [vicnoah/ego-component#1]
请问配置文件的 aesKeyPasswd = "" # 微信支付aes加密密码 这个参数怎么是哪个

**Comment by vicnoah** [comment]
> 请问配置文件的 aesKeyPasswd = "" # 微信支付aes加密密码 这个参数怎么是哪个

是微信商户后台初次登录会提示设置的一个密码，你可以参考我引用的微信支付sdk的官方文档

**Comment by vicnoah** [comment]
> 请问配置文件的 aesKeyPasswd = "" # 微信支付aes加密密码 这个参数怎么是哪个

是微信商户后台初次登录会提示设置的一个密码，你可以参考我引用的微信支付sdk的官方文档

**Comment by vicnoah** [comment]
> 请问配置文件的 aesKeyPasswd = "" # 微信支付aes加密密码 这个参数怎么是哪个

这个密码是微信商户后台设置的APIv3密钥,作用是用于部分加密的接口进行数据解密
