### ISSUE TITLE
能不能出个用参数初始化支付的方法

### ISSUE THREAD

**Issue by Jetereting** [vicnoah/ego-component#2]
Load方法得按指定方式的配置文件，不容易放到其他项目里

**Comment by vicnoah** [comment]
> Load方法得按指定方式的配置文件，不容易放到其他项目里

这个库是为了适配ego框架的，不是为了兼容其它方式而使用的。https://github.com/gotomicro/ego

**Comment by vicnoah** [comment]
> Load方法得按指定方式的配置文件，不容易放到其他项目里

你是在使用ego框架吗？如果不是在ego框架中使用可考虑将组件抽出为一个单独的项目,这个项目仅仅是我在使用ego框架开发时为解决我的问题而写的，项目本身也不够完善。微信官方在完善go的支付sdk要是不着急可以等着用微信官方的

**Comment by Jetereting** [comment]
收到，看您项目里每天更新微信证书文件，不更换的会怎么样

**Comment by vicnoah** [comment]
> 收到，看您项目里每天更新微信证书文件，不更换的会怎么样

可能会出现接口认证问题，微信官方建议定时更新。可以用cron来做定时更新

**Comment by Jetereting** [comment]
收到 谢谢
